version: '3.8'
services:
  web:
    build: .
    ports:
      - "3000:80"
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "4000:4000"
    restart: unless-stopped
    volumes:
      - ./tracks:/app/tracks
